name: tf-dev-network

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "envs/dev/network/**"

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    permissions:
          id-token: write
          contents: read        
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/dev/network
    steps:
      - uses: actions/checkout@v4

      - name: Debug refs
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::817041139478:role/GitAdmin
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: envs/dev/network/tfplan

  apply:
    permissions:
          id-token: write
          contents: read  
    needs: plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/dev/network
    steps:
      - uses: actions/checkout@v4

      - name: Debug refs
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::817041139478:role/GitAdmin
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: envs/dev/network

      - name: Terraform Apply (approved)
        run: terraform apply -auto-approve tfplan
